export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const OPEN_STUDENT = 'OPEN_STUDENT';
export const HANDLE_ALERT_DISMISS = 'HANDLE_ALERT_DISMISS';

